/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreatePost201,
  CreatePostBody,
  GetAllPosts200Item,
  GetPost200
} from '../myAPI.schemas'



  /**
 * @summary Create a post
 */
export const createPost = <TData = AxiosResponse<CreatePost201>>(
    createPostBody: CreatePostBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3123/posts`,
      createPostBody,options
    );
  }
export const getAllPosts = <TData = AxiosResponse<GetAllPosts200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3123/posts`,options
    );
  }
/**
 * @summary Get a post by id
 */
export const getPost = <TData = AxiosResponse<GetPost200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3123/posts/${id}`,options
    );
  }
export type CreatePostResult = AxiosResponse<CreatePost201>
export type GetAllPostsResult = AxiosResponse<GetAllPosts200Item[]>
export type GetPostResult = AxiosResponse<GetPost200>
