/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetAllUsers200Item
} from '../myAPI.schemas'
import { myRequest } from '../../lib/utils/myAxios';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * @summary Get all users
 */
export const getAllUsers = (
    
 options?: SecondParameter<typeof myRequest>,) => {
      return myRequest<GetAllUsers200Item[]>(
      {url: `/users`, method: 'GET'
    },
      options);
    }
  export type GetAllUsersResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
