/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary Get user todos
 */
export const getUserTodos200ResponseItem = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "description": zod.string(),
  "doneAt": zod.string().datetime().nullable(),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})
export const getUserTodos200Response = zod.array(getUserTodos200ResponseItem)

/**
 * @summary Create todo
 */
export const createTodoBody = zod.object({
  "description": zod.string()
})

export const createTodo200Response = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "description": zod.string(),
  "doneAt": zod.string().datetime().nullable(),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})

/**
 * @summary Update todo
 */
export const updateTodoParams = zod.object({
  "todoId": zod.number().nullable()
})

export const updateTodoBody = zod.object({
  "description": zod.string().optional(),
  "doneAt": zod.string().datetime().nullish()
})

export const updateTodo200Response = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "description": zod.string(),
  "doneAt": zod.string().datetime().nullable(),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})

export const updateTodo403Response = zod.enum(['You are not authorized to update this to-do'])

export const updateTodo404Response = zod.enum(['To-do not found'])

/**
 * @summary Delete todo
 */
export const deleteTodoParams = zod.object({
  "todoId": zod.number().nullable()
})

export const deleteTodo204Response = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "description": zod.string(),
  "doneAt": zod.string().datetime().nullable(),
  "createdAt": zod.string().datetime(),
  "updatedAt": zod.string().datetime()
})

export const deleteTodo403Response = zod.enum(['You are not authorized to update this to-do'])

export const deleteTodo404Response = zod.enum(['To-do not found'])

