/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  CreateTodo200,
  CreateTodoBody,
  DeleteTodo204,
  GetUserTodos200Item,
  UpdateTodo200,
  UpdateTodoBody
} from '../myAPI.schemas'



  /**
 * @summary Get user todos
 */
export const getUserTodos = <TData = AxiosResponse<GetUserTodos200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3123/todos`,options
    );
  }
/**
 * @summary Create todo
 */
export const createTodo = <TData = AxiosResponse<CreateTodo200>>(
    createTodoBody: CreateTodoBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3123/todos`,
      createTodoBody,options
    );
  }
/**
 * @summary Update todo
 */
export const updateTodo = <TData = AxiosResponse<UpdateTodo200>>(
    todoId: number | null,
    updateTodoBody: UpdateTodoBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://localhost:3123/todos/${todoId}`,
      updateTodoBody,options
    );
  }
/**
 * @summary Delete todo
 */
export const deleteTodo = <TData = AxiosResponse<DeleteTodo204>>(
    todoId: number | null, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:3123/todos/${todoId}`,options
    );
  }
export type GetUserTodosResult = AxiosResponse<GetUserTodos200Item[]>
export type CreateTodoResult = AxiosResponse<CreateTodo200>
export type UpdateTodoResult = AxiosResponse<UpdateTodo200>
export type DeleteTodoResult = AxiosResponse<DeleteTodo204>
