/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  GetMe200,
  SignIn200,
  SignInBody,
  SignUp201,
  SignUpBody
} from '../myAPI.schemas'



  /**
 * @summary Create user account
 */
export const signUp = <TData = AxiosResponse<SignUp201>>(
    signUpBody: SignUpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3123/sign-up`,
      signUpBody,options
    );
  }
/**
 * @summary Sign in user
 */
export const signIn = <TData = AxiosResponse<SignIn200>>(
    signInBody: SignInBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3123/sign-in`,
      signInBody,options
    );
  }
/**
 * @summary Get current user
 */
export const getMe = <TData = AxiosResponse<GetMe200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:3123/me`,options
    );
  }
export type SignUpResult = AxiosResponse<SignUp201>
export type SignInResult = AxiosResponse<SignIn200>
export type GetMeResult = AxiosResponse<GetMe200>
