/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  SignUp201,
  SignUpBody
} from '../myAPI.schemas'



  /**
 * @summary Create user account
 */
export const signUp = <TData = AxiosResponse<SignUp201>>(
    signUpBody: SignUpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:3123/sign-up`,
      signUpBody,options
    );
  }
export type SignUpResult = AxiosResponse<SignUp201>
