openapi: 3.0.2
paths:
  /posts:
    post:
      summary: Create a post
      tags:
        - posts
      parameters: []
      operationId: createPost
      requestBody:
        description: Body
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
              required:
                - title
                - body
      responses:
        '201':
          description: '201'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  body:
                    type: string
                required:
                  - id
                  - title
                  - body
  /posts/{id}:
    get:
      summary: Get a post by id
      tags:
        - posts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      operationId: getPost
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  body:
                    type: string
                required:
                  - id
                  - title
                  - body
        '202':
          description: '202'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  body:
                    type: string
                required:
                  - title
                  - body
        '404':
          description: '404'
          content:
            application/json:
              schema:
                type: string
                format: 'null'
                nullable: true
info:
  title: My API
  version: 1.0.0
