/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
export type GetPost202 = {
  body: string;
  id?: string;
  title: string;
};

export type GetPost200 = {
  body: string;
  id: string;
  title: string;
};

export type CreatePost201 = {
  body: string;
  id: string;
  title: string;
};

export type CreatePostBody = {
  body: string;
  title: string;
};

